
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_transpose = torch.nn.ConvTranspose2d(12, 11, 2, stride=1, padding=0)
        self.conv_transpose1 = torch.nn.ConvTranspose2d(11, 10, 2, stride=1, padding=0)
        self.conv_transpose2 = torch.nn.ConvTranspose2d(10, 9, 2, stride=1, padding=0)
        self.conv_transpose3 = torch.nn.ConvTranspose2d(9, 8, 2, stride=1, padding=0)
        self.conv_transpose4 = torch.nn.ConvTranspose2d(8, 7, 2, stride=1, padding=0)
        self.conv_transpose5 = torch.nn.ConvTranspose2d(7, 6, 2, stride=1, padding=0)
        self.conv_transpose6 = torch.nn.ConvTranspose2d(6, 5, 2, stride=1, padding=0)
        self.conv_transpose7 = torch.nn.ConvTranspose2d(5, 4, 2, stride=1, padding=0)
        self.conv_transpose8 = torch.nn.ConvTranspose2d(4, 3, 2, stride=1, padding=0)
        self.conv_transpose9 = torch.nn.ConvTranspose2d(3, 2, 2, stride=1, padding=0)
        self.conv_transpose10 = torch.nn.ConvTranspose2d(2, 1, 2, stride=1, padding=0)
    def forward(self, x1):
        v1 = self.conv_transpose(x1)
        v2 = torch.relu(v1)
        v3 = self.conv_transpose1(v2)
        v4 = torch.relu(v3)
        v5 = self.conv_transpose2(v4)
        v6 = torch.relu(v5)
        v7 = self.conv_transpose3(v6)
        v8 = torch.relu(v7)
        v9 = self.conv_transpose4(v8)
        v10 = torch.relu(v9)
        v11 = self.conv_transpose5(v10)
        v12 = torch.relu(v11)
        v13 = self.conv_transpose6(v12)
        v14 = torch.relu(v13)
        v15 = self.conv_transpose7(v14)
        v16 = torch.relu(v15)
        v17 = self.conv_transpose8(v16)
        v18 = torch.relu(v17)
        v19 = self.conv_transpose9(v18)
        v20 = torch.relu(v19)
        v21 = self.conv_transpose10(v20)
        v22 = torch.sigmoid(v21)
        return v22
# Inputs to the model
x1 = torch.randn(1, 12, 50, 50)
