# execution result
RES_KEY = "results"
RESULT_KEY = "res"
ERROR_KEY = "err"
ERR_ARG_KEY = "error_args"
ERR_CPU_KEY = "err_cpu"
ERR_GPU_KEY = "err_gpu"
RES_CPU_KEY = "res_cpu"
RES_GPU_KEY = "res_gpu"
ERR_HIGH_KEY = "err_high"
ERR_LOW_KEY = "err_low"
RES_HIGH_KEY = "res_high"
RES_LOW_KEY = "res_low"
TIME_LOW_KEY = "time_low"
TIME_HIGH_KEY = "time_high"

ERR_1 = "err_1"
ERR_2 = "err_2"
RES_1 = "res_1"
RES_2 = "res_2"
GRAD_RES_1 = "grad_res_1"
GRAD_RES_2 = "grad_res_2"
GRAD_ERR_1 = "grad_err_1"
GRAD_ERR_2 = "grad_err_2"

ERR_FN = "err_fn"
ERR_CHECK = "err_check"
