
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x1, x2, x3, inp):
        v1 = torch.mm(x1, x2)
        tmp1 = torch.mm(x3, x3)
        v2 = v1 + tmp1
        v3 = v2 + inp
        return v3
# Inputs to the model
x1 = torch.randn(3, 3)
x2 = torch.randn(3, 3)
x3 = inp # Notice how the 'inp' tensor is reused to store a tensor generated by another computation, and used for output
inp = torch.randn(3, 3)
