
class ModelTanh(torch.nn.Module):
    def __init__(self):
        super(ModelTanh, self).__init__()
        self.conv_1 = torch.nn.Conv2d(in_channels = 3, out_channels = 32, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_2 = torch.nn.Conv2d(in_channels = 32, out_channels = 32, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_5 = torch.nn.Conv2d(in_channels = 32, out_channels = 64, kernel_size = 3, stride = 2, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_6 = torch.nn.Conv2d(in_channels = 64, out_channels = 64, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_7 = torch.nn.Conv2d(in_channels = 64, out_channels = 64, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_10 = torch.nn.Conv2d(in_channels = 64, out_channels = 128, kernel_size = 3, stride = 2, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_11 = torch.nn.Conv2d(in_channels = 128, out_channels = 128, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_12 = torch.nn.Conv2d(in_channels = 128, out_channels = 128, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_15 = torch.nn.Conv2d(in_channels = 128, out_channels = 256, kernel_size = 3, stride = 2, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_16 = torch.nn.Conv2d(in_channels = 256, out_channels = 256, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_17 = torch.nn.Conv2d(in_channels = 256, out_channels = 256, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_20 = torch.nn.Conv2d(in_channels = 256, out_channels = 512, kernel_size = 3, stride = 2, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_21 = torch.nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_22 = torch.nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 1, dilation = 1, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_24 = torch.nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 2, dilation = 2, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_25 = torch.nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 4, dilation = 4, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_26 = torch.nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 8, dilation = 8, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_28 = torch.nn.Conv2d(in_channels = 512, out_channels = 1, kernel_size = 3, stride = 1, padding = 16, dilation = 16, groups = 1, bias = True, padding_mode = 'zeros')
        self.conv_29 = torch.nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 2, stride = 2, bias = False)
    def forward(self, x):
        x_1 = self.conv_1(x)
        x_2 = torch.tanh(x_1)
        x_3 = self.conv_2(x_2)
        x_4 = torch.tanh(x_3)
        x_5 = self.conv_5(x_4)
        x_6 = torch.tanh(x_5)
        x_7 = self.conv_6(x_6)
        x_8 = torch.tanh(x_7)
        x_9 = self.conv_7(x_8)
        x_10 = torch.tanh(x_9)
        x_11 = self.conv_10(x_10)
        x_12 = torch.tanh(x_11)
        x_13 = self.conv_11(x_12)
        x_14 = torch.relu(x_13)
        x_15 = self.conv_12(x_14)
        x_16 = torch.tanh(x_15)
        x_17 = self.conv_15(x_16)
        x_18 = torch.tanh(x_17)
        x_19 = self.conv_16(x_18)
        x_20 = torch.relu(x_19)
        x_21 = self.conv_17(x_20)
        x_22 = torch.tanh(x_21)
        x_23 = self.conv_20(x_22)
        x_24 = torch.tanh(x_23)
        x_25 = self.conv_21(x_24)
        x_26 = torch.relu(x_25)
        x_27 = self.conv_22(x_26)
        x_28 = torch.tanh(x_27)
        x_29 = self.conv_24(x_28)
        x_30 = torch.tanh(x_29)
        x_31 = self.conv_25(x_30)
        x_32 = torch.tanh(x_31)
        x_33 = self.conv_26(x_32)
        x_34 = torch.relu(x_33)
        x_35 = self.conv_28(x_34)
        x_36 = torch.tanh(x_35)
        x_37 = self.conv_29(x)
        x_38 = torch.div(x_37, 16777216.0)
        x_39 = torch.sub(x_36, x_38)
        x_40 = torch.mul(x_39, x_39)
        x_41 = torch.sum(x_40)
        x_42 = torch.add(x_41, 0.1)
        x_43 = torch.sqrt(x_42)
        x_44 = torch.div(x_36, x_43)
        x_45 = torch.clamp(x_44, 0.0, 6.0)
        return x_45
# Inputs to the model
x = torch.randn(1, 3, 64, 64)
