
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.relu = torch.nn.ReLU()
        self.conv = torch.nn.Conv2d(64, 64, 1, stride=1, padding=1)
        self.relu2 = torch.nn.ReLU()
        self.conv2 = torch.nn.Conv2d(64, 64, 1, stride=1, padding=1)
        self.relu3 = torch.nn.ReLU()
        self.conv3 = torch.nn.Conv2d(64, 64, 1, stride=1, padding=1)
        self.relu4 = torch.nn.ReLU()
        self.conv4 = torch.nn.Conv2d(64, 64, 1, stride=1, padding=1)
        self.relu5 = torch.nn.ReLU()
        self.conv5 = torch.nn.Conv2d(64, 128, 1, stride=1, padding=0)
        self.relu6 = torch.nn.ReLU()
        self.conv6 = torch.nn.Conv2d(128, 128, 1, stride=1, padding=1)
        self.relu7 = torch.nn.ReLU()
        self.conv7 = torch.nn.Conv2d(128, 128, 1, stride=1, padding=1)
        self.relu8 = torch.nn.ReLU()
        self.conv8 = torch.nn.Conv2d(128, 64, 1, stride=1, padding=1)
        self.relu9 = torch.nn.ReLU()
        self.conv9 = torch.nn.Conv2d(64, 64, 1, stride=1, padding=1)
        self.relu10 = torch.nn.ReLU()
        self.conv10 = torch.nn.Conv2d(64, 64, 1, stride=1, padding=0)
        self.relu11 = torch.nn.ReLU()
        self.conv11 = torch.nn.Conv2d(64, 16, 1, stride=1, padding=1)
        self.relu12 = torch.nn.ReLU()
        self.conv12 = torch.nn.Conv2d(16, 16, 1, stride=1, padding=1)
    def forward(self, x):
        y = self.relu(x)
        y = self.conv(y)
        y = self.relu2(y)
        y = self.conv2(y)
        y = self.relu3(y)
        y = self.conv3(y)
        y = self.relu4(y)
        y = self.conv4(y)
        y = self.relu5(y)
        y = self.conv5(y)
        y = self.relu6(y)
        y = self.conv6(y)
        y = self.relu7(y)
        y = self.conv7(y)
        y = self.relu8(y)
        y = self.conv8(y)
        y = self.relu9(y)
        y = self.conv9(y)
        y = self.relu10(y)
        y = self.conv10(y)
        y = self.relu11(y)
        y = self.conv11(y)
        y = torch.tanh(y)
        y = self.relu12(y)
        y = self.conv12(y)
        return y
# Inputs to the model
x = torch.randn(1, 64, 32, 32)
